# Generated by Django 3.1.7 on 2021-05-29 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('contact_no', models.IntegerField()),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qty', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='RestManage.customer')),
                ('product_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='RestManage.product')),
            ],
        ),
    ]
